// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AlertChannelType.
const (
	Discord AlertChannelType = "discord"
	Email   AlertChannelType = "email"
	Slack   AlertChannelType = "slack"
	Webhook AlertChannelType = "webhook"
)

// Valid indicates whether the value is a known member of the AlertChannelType enum.
func (e AlertChannelType) Valid() bool {
	switch e {
	case Discord:
		return true
	case Email:
		return true
	case Slack:
		return true
	case Webhook:
		return true
	default:
		return false
	}
}

// Defines values for AlertEventStatus.
const (
	Firing   AlertEventStatus = "firing"
	Resolved AlertEventStatus = "resolved"
)

// Valid indicates whether the value is a known member of the AlertEventStatus enum.
func (e AlertEventStatus) Valid() bool {
	switch e {
	case Firing:
		return true
	case Resolved:
		return true
	default:
		return false
	}
}

// Defines values for AlertRuleType.
const (
	AlertRuleTypeCronMissed  AlertRuleType = "cron_missed"
	AlertRuleTypeErrorSpike  AlertRuleType = "error_spike"
	AlertRuleTypeMonitorDown AlertRuleType = "monitor_down"
)

// Valid indicates whether the value is a known member of the AlertRuleType enum.
func (e AlertRuleType) Valid() bool {
	switch e {
	case AlertRuleTypeCronMissed:
		return true
	case AlertRuleTypeErrorSpike:
		return true
	case AlertRuleTypeMonitorDown:
		return true
	default:
		return false
	}
}

// Defines values for AuthUserTier.
const (
	Free AuthUserTier = "free"
	Pro  AuthUserTier = "pro"
	Team AuthUserTier = "team"
)

// Valid indicates whether the value is a known member of the AuthUserTier enum.
func (e AuthUserTier) Valid() bool {
	switch e {
	case Free:
		return true
	case Pro:
		return true
	case Team:
		return true
	default:
		return false
	}
}

// Defines values for CreateAlertRuleRequestType.
const (
	CreateAlertRuleRequestTypeCronMissed  CreateAlertRuleRequestType = "cron_missed"
	CreateAlertRuleRequestTypeErrorSpike  CreateAlertRuleRequestType = "error_spike"
	CreateAlertRuleRequestTypeMonitorDown CreateAlertRuleRequestType = "monitor_down"
)

// Valid indicates whether the value is a known member of the CreateAlertRuleRequestType enum.
func (e CreateAlertRuleRequestType) Valid() bool {
	switch e {
	case CreateAlertRuleRequestTypeCronMissed:
		return true
	case CreateAlertRuleRequestTypeErrorSpike:
		return true
	case CreateAlertRuleRequestTypeMonitorDown:
		return true
	default:
		return false
	}
}

// Defines values for CronMonitorStatus.
const (
	CronMonitorStatusHealthy CronMonitorStatus = "healthy"
	CronMonitorStatusLate    CronMonitorStatus = "late"
	CronMonitorStatusMissed  CronMonitorStatus = "missed"
	CronMonitorStatusUnknown CronMonitorStatus = "unknown"
)

// Valid indicates whether the value is a known member of the CronMonitorStatus enum.
func (e CronMonitorStatus) Valid() bool {
	switch e {
	case CronMonitorStatusHealthy:
		return true
	case CronMonitorStatusLate:
		return true
	case CronMonitorStatusMissed:
		return true
	case CronMonitorStatusUnknown:
		return true
	default:
		return false
	}
}

// Defines values for ErrorResponseErrorCode.
const (
	ErrorResponseErrorCodeBadRequest        ErrorResponseErrorCode = "bad_request"
	ErrorResponseErrorCodeConflict          ErrorResponseErrorCode = "conflict"
	ErrorResponseErrorCodeForbidden         ErrorResponseErrorCode = "forbidden"
	ErrorResponseErrorCodeInternalError     ErrorResponseErrorCode = "internal_error"
	ErrorResponseErrorCodeNotFound          ErrorResponseErrorCode = "not_found"
	ErrorResponseErrorCodeRateLimited       ErrorResponseErrorCode = "rate_limited"
	ErrorResponseErrorCodeTierLimitExceeded ErrorResponseErrorCode = "tier_limit_exceeded"
	ErrorResponseErrorCodeUnauthorized      ErrorResponseErrorCode = "unauthorized"
)

// Valid indicates whether the value is a known member of the ErrorResponseErrorCode enum.
func (e ErrorResponseErrorCode) Valid() bool {
	switch e {
	case ErrorResponseErrorCodeBadRequest:
		return true
	case ErrorResponseErrorCodeConflict:
		return true
	case ErrorResponseErrorCodeForbidden:
		return true
	case ErrorResponseErrorCodeInternalError:
		return true
	case ErrorResponseErrorCodeNotFound:
		return true
	case ErrorResponseErrorCodeRateLimited:
		return true
	case ErrorResponseErrorCodeTierLimitExceeded:
		return true
	case ErrorResponseErrorCodeUnauthorized:
		return true
	default:
		return false
	}
}

// Defines values for LogRecordLevel.
const (
	LogRecordLevelDebug LogRecordLevel = "debug"
	LogRecordLevelError LogRecordLevel = "error"
	LogRecordLevelFatal LogRecordLevel = "fatal"
	LogRecordLevelInfo  LogRecordLevel = "info"
	LogRecordLevelTrace LogRecordLevel = "trace"
	LogRecordLevelWarn  LogRecordLevel = "warn"
)

// Valid indicates whether the value is a known member of the LogRecordLevel enum.
func (e LogRecordLevel) Valid() bool {
	switch e {
	case LogRecordLevelDebug:
		return true
	case LogRecordLevelError:
		return true
	case LogRecordLevelFatal:
		return true
	case LogRecordLevelInfo:
		return true
	case LogRecordLevelTrace:
		return true
	case LogRecordLevelWarn:
		return true
	default:
		return false
	}
}

// Defines values for MonitorStatus.
const (
	MonitorStatusDown    MonitorStatus = "down"
	MonitorStatusUnknown MonitorStatus = "unknown"
	MonitorStatusUp      MonitorStatus = "up"
)

// Valid indicates whether the value is a known member of the MonitorStatus enum.
func (e MonitorStatus) Valid() bool {
	switch e {
	case MonitorStatusDown:
		return true
	case MonitorStatusUnknown:
		return true
	case MonitorStatusUp:
		return true
	default:
		return false
	}
}

// Defines values for PollTokenResponseStatus.
const (
	Authorized PollTokenResponseStatus = "authorized"
	Pending    PollTokenResponseStatus = "pending"
	SlowDown   PollTokenResponseStatus = "slow_down"
)

// Valid indicates whether the value is a known member of the PollTokenResponseStatus enum.
func (e PollTokenResponseStatus) Valid() bool {
	switch e {
	case Authorized:
		return true
	case Pending:
		return true
	case SlowDown:
		return true
	default:
		return false
	}
}

// Defines values for QueryLogsParamsLevel.
const (
	QueryLogsParamsLevelDebug QueryLogsParamsLevel = "debug"
	QueryLogsParamsLevelError QueryLogsParamsLevel = "error"
	QueryLogsParamsLevelFatal QueryLogsParamsLevel = "fatal"
	QueryLogsParamsLevelInfo  QueryLogsParamsLevel = "info"
	QueryLogsParamsLevelTrace QueryLogsParamsLevel = "trace"
	QueryLogsParamsLevelWarn  QueryLogsParamsLevel = "warn"
)

// Valid indicates whether the value is a known member of the QueryLogsParamsLevel enum.
func (e QueryLogsParamsLevel) Valid() bool {
	switch e {
	case QueryLogsParamsLevelDebug:
		return true
	case QueryLogsParamsLevelError:
		return true
	case QueryLogsParamsLevelFatal:
		return true
	case QueryLogsParamsLevelInfo:
		return true
	case QueryLogsParamsLevelTrace:
		return true
	case QueryLogsParamsLevelWarn:
		return true
	default:
		return false
	}
}

// AlertChannel defines model for AlertChannel.
type AlertChannel struct {
	// Destination Email address, Slack webhook URL, PagerDuty routing key, or webhook URL.
	Destination *string          `json:"destination,omitempty"`
	Type        AlertChannelType `json:"type"`
}

// AlertChannelType defines model for AlertChannel.Type.
type AlertChannelType string

// AlertEvent defines model for AlertEvent.
type AlertEvent struct {
	// Details Rule-type-specific context about why the alert fired.
	Details    *map[string]interface{} `json:"details,omitempty"`
	FiredAt    time.Time               `json:"fired_at"`
	Id         openapi_types.UUID      `json:"id"`
	ProjectId  openapi_types.UUID      `json:"project_id"`
	ResolvedAt *time.Time              `json:"resolved_at,omitempty"`
	RuleId     openapi_types.UUID      `json:"rule_id"`
	RuleName   string                  `json:"rule_name"`
	Status     AlertEventStatus        `json:"status"`
}

// AlertEventStatus defines model for AlertEvent.Status.
type AlertEventStatus string

// AlertRule defines model for AlertRule.
type AlertRule struct {
	Channels []AlertChannel `json:"channels"`

	// Condition Rule-type-specific condition parameters.
	Condition map[string]interface{} `json:"condition"`
	CreatedAt time.Time              `json:"created_at"`
	Enabled   bool                   `json:"enabled"`
	Id        openapi_types.UUID     `json:"id"`
	Name      string                 `json:"name"`
	ProjectId openapi_types.UUID     `json:"project_id"`

	// Type Kind of event that triggers this rule.
	Type AlertRuleType `json:"type"`
}

// AlertRuleType Kind of event that triggers this rule.
type AlertRuleType string

// AuthResponse Returned by OAuth callback and refresh endpoints.
// Contains a short-lived access token and a single-use refresh token.
type AuthResponse struct {
	// AccessToken Muga access token (24h lifetime). Use as `Authorization: Bearer <token>`.
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Muga refresh token (30d lifetime, single-use). Use with `POST /auth/refresh`.
	RefreshToken string   `json:"refresh_token"`
	TokenType    string   `json:"token_type"`
	User         AuthUser `json:"user"`
}

// AuthUser defines model for AuthUser.
type AuthUser struct {
	Email string             `json:"email"`
	Id    openapi_types.UUID `json:"id"`

	// IsNew True if the account was just created (first login).
	IsNew *bool        `json:"is_new,omitempty"`
	Name  string       `json:"name"`
	Tier  AuthUserTier `json:"tier"`
}

// AuthUserTier defines model for AuthUser.Tier.
type AuthUserTier string

// BillingSessionResponse defines model for BillingSessionResponse.
type BillingSessionResponse struct {
	// Url Redirect URL for the Stripe-hosted session.
	Url string `json:"url"`
}

// ChartBucket defines model for ChartBucket.
type ChartBucket struct {
	Count int `json:"count"`

	// Timestamp Start of the bucket interval.
	Timestamp time.Time `json:"timestamp"`
}

// CheckoutRequest defines model for CheckoutRequest.
type CheckoutRequest struct {
	// CancelUrl URL Stripe redirects to if the user cancels.
	CancelUrl *string `json:"cancel_url,omitempty"`

	// Plan Plan identifier to subscribe to.
	Plan string `json:"plan"`

	// SuccessUrl URL Stripe redirects to after a successful checkout.
	SuccessUrl *string `json:"success_url,omitempty"`
}

// CreateAlertRuleRequest defines model for CreateAlertRuleRequest.
type CreateAlertRuleRequest struct {
	Channels  []AlertChannel             `json:"channels"`
	Condition map[string]interface{}     `json:"condition"`
	Enabled   *bool                      `json:"enabled,omitempty"`
	Name      string                     `json:"name"`
	Type      CreateAlertRuleRequestType `json:"type"`
}

// CreateAlertRuleRequestType defines model for CreateAlertRuleRequest.Type.
type CreateAlertRuleRequestType string

// CreateCronMonitorRequest defines model for CreateCronMonitorRequest.
type CreateCronMonitorRequest struct {
	ExpectedIntervalSeconds int    `json:"expected_interval_seconds"`
	GraceSeconds            int    `json:"grace_seconds"`
	Name                    string `json:"name"`
}

// CreateMonitorRequest defines model for CreateMonitorRequest.
type CreateMonitorRequest struct {
	IntervalSeconds int    `json:"interval_seconds"`
	Name            string `json:"name"`
	Url             string `json:"url"`
}

// CreateProjectRequest defines model for CreateProjectRequest.
type CreateProjectRequest struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

// CreateTokenRequest defines model for CreateTokenRequest.
type CreateTokenRequest struct {
	Name string `json:"name"`
}

// CreatedToken defines model for CreatedToken.
type CreatedToken struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`

	// Prefix First characters of the token, safe to display.
	Prefix    string             `json:"prefix"`
	ProjectId openapi_types.UUID `json:"project_id"`

	// Token Full plaintext token value. Shown only once — store it securely.
	Token string `json:"token"`
}

// CronMonitor defines model for CronMonitor.
type CronMonitor struct {
	CreatedAt time.Time `json:"created_at"`

	// ExpectedIntervalSeconds How often the job is expected to run.
	ExpectedIntervalSeconds int `json:"expected_interval_seconds"`

	// GraceSeconds Extra time allowed beyond the expected interval before alerting.
	GraceSeconds int                `json:"grace_seconds"`
	Id           openapi_types.UUID `json:"id"`
	LastPingAt   *time.Time         `json:"last_ping_at,omitempty"`
	Name         string             `json:"name"`
	ProjectId    openapi_types.UUID `json:"project_id"`
	Status       CronMonitorStatus  `json:"status"`
}

// CronMonitorStatus defines model for CronMonitor.Status.
type CronMonitorStatus string

// DeviceFlowResponse defines model for DeviceFlowResponse.
type DeviceFlowResponse struct {
	// DeviceCode Opaque device code to use when polling `/auth/token`.
	DeviceCode string `json:"device_code"`

	// ExpiresIn Seconds until the device code expires.
	ExpiresIn int `json:"expires_in"`

	// Interval Recommended polling interval in seconds.
	Interval int `json:"interval"`

	// UserCode Short code the user must enter at `verification_uri`.
	UserCode string `json:"user_code"`

	// VerificationUri URL the user must visit to approve the request.
	VerificationUri string `json:"verification_uri"`
}

// ErrorGroup defines model for ErrorGroup.
type ErrorGroup struct {
	// Count Number of occurrences in the queried time window.
	Count int `json:"count"`

	// Fingerprint Stable hash identifying this error group.
	Fingerprint string             `json:"fingerprint"`
	FirstSeenAt time.Time          `json:"first_seen_at"`
	LastSeenAt  time.Time          `json:"last_seen_at"`
	ProjectId   openapi_types.UUID `json:"project_id"`
	Service     string             `json:"service"`

	// Title Short description derived from the exception type and message.
	Title string `json:"title"`
}

// ErrorGroupDetail defines model for ErrorGroupDetail.
type ErrorGroupDetail struct {
	// Chart Occurrence counts bucketed by hour (most recent first).
	Chart *[]ChartBucket `json:"chart,omitempty"`

	// Count Number of occurrences in the queried time window.
	Count int `json:"count"`

	// Fingerprint Stable hash identifying this error group.
	Fingerprint string             `json:"fingerprint"`
	FirstSeenAt time.Time          `json:"first_seen_at"`
	LastSeenAt  time.Time          `json:"last_seen_at"`
	ProjectId   openapi_types.UUID `json:"project_id"`

	// RecentOccurrences Up to 10 most recent log records for this group.
	RecentOccurrences *[]LogRecord `json:"recent_occurrences,omitempty"`
	Service           string       `json:"service"`

	// StackTrace Representative stack trace for this error group.
	StackTrace *string `json:"stack_trace,omitempty"`

	// Title Short description derived from the exception type and message.
	Title string `json:"title"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error struct {
		Code ErrorResponseErrorCode `json:"code"`

		// Message Human-readable error description.
		Message string `json:"message"`
	} `json:"error"`
}

// ErrorResponseErrorCode defines model for ErrorResponse.Error.Code.
type ErrorResponseErrorCode string

// LogRecord defines model for LogRecord.
type LogRecord struct {
	// Attributes Structured key-value pairs attached to the log record.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`

	// Body Log message body.
	Body string `json:"body"`

	// Id Unique record identifier.
	Id        string             `json:"id"`
	Level     LogRecordLevel     `json:"level"`
	ProjectId openapi_types.UUID `json:"project_id"`
	Service   string             `json:"service"`
	SpanId    *string            `json:"span_id,omitempty"`
	Timestamp time.Time          `json:"timestamp"`
	TraceId   *string            `json:"trace_id,omitempty"`
}

// LogRecordLevel defines model for LogRecord.Level.
type LogRecordLevel string

// Monitor defines model for Monitor.
type Monitor struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// IntervalSeconds How often the monitor polls the URL.
	IntervalSeconds int                `json:"interval_seconds"`
	LastCheckedAt   *time.Time         `json:"last_checked_at,omitempty"`
	Name            string             `json:"name"`
	ProjectId       openapi_types.UUID `json:"project_id"`
	Status          MonitorStatus      `json:"status"`
	Url             string             `json:"url"`
}

// MonitorStatus defines model for Monitor.Status.
type MonitorStatus string

// OidcTokenRequest defines model for OidcTokenRequest.
type OidcTokenRequest struct {
	// Token GitHub Actions OIDC JWT. Obtained in a workflow via
	// `$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://api.muga.sh`.
	Token string `json:"token"`
}

// OidcTokenResponse defines model for OidcTokenResponse.
type OidcTokenResponse struct {
	// AccessToken Muga access token (24h lifetime). No refresh token — use OIDC to re-authenticate.
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn int      `json:"expires_in"`
	TokenType string   `json:"token_type"`
	User      AuthUser `json:"user"`
}

// PaginatedResponse defines model for PaginatedResponse.
type PaginatedResponse struct {
	Data       []interface{} `json:"data"`
	Pagination Pagination    `json:"pagination"`
}

// Pagination defines model for Pagination.
type Pagination struct {
	// HasMore Whether there are additional pages.
	HasMore bool `json:"has_more"`

	// NextCursor Cursor to pass as `cursor` to fetch the next page. Null when `has_more` is false.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PingResponse defines model for PingResponse.
type PingResponse struct {
	Ok       bool      `json:"ok"`
	PingedAt time.Time `json:"pinged_at"`
}

// PollTokenRequest defines model for PollTokenRequest.
type PollTokenRequest struct {
	// DeviceCode Device code returned by `/auth/device`.
	DeviceCode string `json:"device_code"`
}

// PollTokenResponse defines model for PollTokenResponse.
type PollTokenResponse struct {
	// AccessToken Muga access token. Only present when `status` is `authorized`. Expires in `expires_in` seconds.
	AccessToken *string `json:"access_token,omitempty"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn *int `json:"expires_in,omitempty"`

	// RefreshToken Muga refresh token. Only present when `status` is `authorized`. Single-use, 30-day lifetime.
	RefreshToken *string `json:"refresh_token,omitempty"`

	// Status `pending` while waiting for user approval, `slow_down` when the client is polling too fast (must increase interval by 5 s per RFC 8628 §3.5), `authorized` when the user has approved the request.
	Status    PollTokenResponseStatus `json:"status"`
	TokenType *string                 `json:"token_type,omitempty"`
	User      *AuthUser               `json:"user,omitempty"`
}

// PollTokenResponseStatus `pending` while waiting for user approval, `slow_down` when the client is polling too fast (must increase interval by 5 s per RFC 8628 §3.5), `authorized` when the user has approved the request.
type PollTokenResponseStatus string

// PortalRequest defines model for PortalRequest.
type PortalRequest struct {
	// ReturnUrl URL to return the user to after the portal session.
	ReturnUrl *string `json:"return_url,omitempty"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`

	// Slug URL-safe identifier, unique per user.
	Slug string `json:"slug"`
}

// ProjectStatus defines model for ProjectStatus.
type ProjectStatus struct {
	Crons struct {
		Healthy int `json:"healthy"`
		Late    int `json:"late"`
		Missed  int `json:"missed"`
		Total   int `json:"total"`
		Unknown int `json:"unknown"`
	} `json:"crons"`
	Errors struct {
		// New24h Error groups seen for the first time in the last 24 hours.
		New24h int `json:"new_24h"`

		// Total24h Total error occurrences in the last 24 hours.
		Total24h int `json:"total_24h"`
	} `json:"errors"`
	Logs struct {
		// Volume24h Total log records ingested in the last 24 hours.
		Volume24h int `json:"volume_24h"`
	} `json:"logs"`
	Monitors struct {
		Down    int `json:"down"`
		Total   int `json:"total"`
		Unknown int `json:"unknown"`
		Up      int `json:"up"`
	} `json:"monitors"`
	ProjectId openapi_types.UUID `json:"project_id"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	// RefreshToken The refresh token from a previous auth or refresh response.
	// Single-use — a new refresh token is returned with each call.
	RefreshToken string `json:"refresh_token"`
}

// Token defines model for Token.
type Token struct {
	CreatedAt  time.Time          `json:"created_at"`
	Id         openapi_types.UUID `json:"id"`
	LastUsedAt *time.Time         `json:"last_used_at,omitempty"`
	Name       string             `json:"name"`

	// Prefix First characters of the token, safe to display.
	Prefix    string             `json:"prefix"`
	ProjectId openapi_types.UUID `json:"project_id"`
}

// Cursor defines model for cursor.
type Cursor = string

// Id defines model for id.
type Id = openapi_types.UUID

// Limit defines model for limit.
type Limit = int

// ProjectId defines model for project_id.
type ProjectId = openapi_types.UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// RateLimited defines model for RateLimited.
type RateLimited = ErrorResponse

// TierLimitExceeded defines model for TierLimitExceeded.
type TierLimitExceeded = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// OauthCallbackParams defines parameters for OauthCallback.
type OauthCallbackParams struct {
	// Code Authorization code from GitHub.
	Code string `form:"code" json:"code"`

	// State CSRF state parameter (must match the value sent in the authorization request).
	State string `form:"state" json:"state"`
}

// InitiateDeviceFlowJSONBody defines parameters for InitiateDeviceFlow.
type InitiateDeviceFlowJSONBody = map[string]interface{}

// ListProjectsParams defines parameters for ListProjects.
type ListProjectsParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAlertRulesParams defines parameters for ListAlertRules.
type ListAlertRulesParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListAlertHistoryParams defines parameters for ListAlertHistory.
type ListAlertHistoryParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Since ISO 8601 timestamp — return events at or after this time
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Until ISO 8601 timestamp — return events before this time
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`
}

// ListCronMonitorsParams defines parameters for ListCronMonitors.
type ListCronMonitorsParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// QueryErrorGroupsParams defines parameters for QueryErrorGroups.
type QueryErrorGroupsParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Service Filter by service name
	Service *string    `form:"service,omitempty" json:"service,omitempty"`
	Since   *time.Time `form:"since,omitempty" json:"since,omitempty"`
	Until   *time.Time `form:"until,omitempty" json:"until,omitempty"`
}

// QueryLogsParams defines parameters for QueryLogs.
type QueryLogsParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Service Filter by service name
	Service *string `form:"service,omitempty" json:"service,omitempty"`

	// Level Minimum severity level
	Level *QueryLogsParamsLevel `form:"level,omitempty" json:"level,omitempty"`

	// Since ISO 8601 timestamp — return records at or after this time
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Until ISO 8601 timestamp — return records before this time
	Until *time.Time `form:"until,omitempty" json:"until,omitempty"`

	// Grep Full-text search string applied to the log body
	Grep *string `form:"grep,omitempty" json:"grep,omitempty"`
}

// QueryLogsParamsLevel defines parameters for QueryLogs.
type QueryLogsParamsLevel string

// ListMonitorsParams defines parameters for ListMonitors.
type ListMonitorsParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	// Cursor Opaque pagination cursor returned in the previous response.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return (1–100, default 20).
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`
}

// InitiateDeviceFlowJSONRequestBody defines body for InitiateDeviceFlow for application/json ContentType.
type InitiateDeviceFlowJSONRequestBody = InitiateDeviceFlowJSONBody

// OidcTokenExchangeJSONRequestBody defines body for OidcTokenExchange for application/json ContentType.
type OidcTokenExchangeJSONRequestBody = OidcTokenRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// PollDeviceTokenJSONRequestBody defines body for PollDeviceToken for application/json ContentType.
type PollDeviceTokenJSONRequestBody = PollTokenRequest

// CreateCheckoutSessionJSONRequestBody defines body for CreateCheckoutSession for application/json ContentType.
type CreateCheckoutSessionJSONRequestBody = CheckoutRequest

// CreatePortalSessionJSONRequestBody defines body for CreatePortalSession for application/json ContentType.
type CreatePortalSessionJSONRequestBody = PortalRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = CreateProjectRequest

// CreateAlertRuleJSONRequestBody defines body for CreateAlertRule for application/json ContentType.
type CreateAlertRuleJSONRequestBody = CreateAlertRuleRequest

// CreateCronMonitorJSONRequestBody defines body for CreateCronMonitor for application/json ContentType.
type CreateCronMonitorJSONRequestBody = CreateCronMonitorRequest

// CreateMonitorJSONRequestBody defines body for CreateMonitor for application/json ContentType.
type CreateMonitorJSONRequestBody = CreateMonitorRequest

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = CreateTokenRequest
